# Generated by Django 5.1.6 on 2025-03-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="consultationFee",
            field=models.IntegerField(null=True),
        ),
    ]
