# Generated by Django 5.1.6 on 2025-03-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="doctorinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eventname", models.CharField(max_length=255)),
                ("organizer", models.CharField(max_length=255)),
                ("note", models.CharField(max_length=255)),
            ],
        ),
    ]
